---
title: "Untitled"
author: "George G. Vega Yon"
date: "4/26/2017"
output: pdf_document
---

\newcommand{\isone}[1]{{\boldsymbol{1}\left\{ #1 \right\}}}
\renewcommand{\Pr}[1]{{\mbox{Pr}\left(#1\right) }}
\newcommand{\Prcond}[2]{{\mbox{Pr}\left(#1\;|\;#2\right) }}

# Definitions

An Annotated Phylogenetic Tree $\tau \equiv (N, E, A)$ is a tuple with nodes $N \equiv \{1 ,\dots, n\}$,  edges $E\equiv \{(i, j) \in N\times N: i\rightarrow j\}$, where $\rightarrow$ denotes 'parent of', and annotations $A \equiv \{a_{ip} \in \{0,1\}: i\in N, p = \{1,\dots,p\}\}$, where $P$ denotes the number of annotations per node. Furthermore, we say that this tree is a Partially Ordered Annotated Phylogenetic Tree if it's nodes' labels form a partial order, this is $i < j, \forall (i, j) \in E$.


# Predicting Leafs Annotations

The ultimate goal of this model is to be able to predict, or rather, impute functional states to leaf nodes for which we do not have information. Using both, the information that we have about the annotated tree and the parameter estimates of our model, we can calculate what is the probability of a leaf $i$ having or not a function $p$. Formally, with $S\equiv (N, E)$, the probability of leaf node $i$ having the function $p$, conditional on the tree structure $S^*$ and the observed set of annotations $A^*$, which excludes annotations on $i$, is:

$$
\tag{1}\label{eq:1}
\Prcond{a_i = 1}{S = S^*, A = A^*} = \frac{\Prcond{A = A^*}{S = S^*, a_i = 1}\times\Prcond{a_i=1}{S = S^*}}{
\Prcond{A = A^*}{S = S^*}
}
$$

For ease of notation, we will drop the $S = S^*$, as all probabilities throughout this section are conditional on the tree structure. Now, we know that

$$
\tag{2}\label{eq:2}
\Pr{A = A^*} = \Prcond{A = A^*}{a_i = 1}\times\Pr{a_i = 1} + \Prcond{A = A^*}{a_i = 0}\times(1 - \Pr{a_i = 1})
$$

Hence, pluging in \eqref{eq:2} into \eqref{eq:1}, and multiplying both numerator and denominator by $1/\Pr{a_i = 1}$, \eqref{eq:1} can be rewritten as

$$
\tag{1'}
\Prcond{a_i = 1}{A = A^*} = \frac{\Prcond{A = A^*}{a_i = 1}}{
\Prcond{A = A^*}{a_i = 1} + \Prcond{A = A^*}{a_i = 0}\times\frac{\left(1 - \Pr{a_i = 1}\right)}{\Pr{a_i = 1}}
}
$$
Where $\Prcond{A = A^*}{a_i = 1}$ is the likelihood of the data given that we set the ith node to be 1, which we already know how to compute. This way, we are only missing $\Pr{a_i=1}$, which we can compute as follows:

$$
\begin{aligned}
\Pr{a_i = 1} & = \pi \Prcond{a_i = 1}{a_0 = 1} + (1 - \pi) \Prcond{a_i = 1}{a_0 = 0}
\end{aligned}
$$

Where, given that $\gamma_{01}$ is the shorest path length between node 0 and node $i$, we have:

$$
\left[\begin{array}{cc}
\Prcond{a_i = 0}{a_0 = 0} & \Prcond{a_i = 1}{a_0 = 0} \\
\Prcond{a_i = 0}{a_0 = 1} & \Prcond{a_i = 1}{a_0 = 1}
\end{array}
\right]
=
\left[\begin{array}{cc}
1 & 0 \\
0 & 1
\end{array} \right] \times
\left[\begin{array}{cc}
1 - \hat\mu_0 &  \hat\mu_0 \\
\hat\mu_1 &  1 - \hat\mu_1
\end{array}
\right]^{\gamma_{0i}}
$$

Finally, we will denote the predicted probability as $\hat a_i = \Prcond{a_i = 1}{S = S^*, A = A^*}$

# Assesment of Model Predictions

Let $A \equiv \{a_{ip}\}_{i\in N, p \in P}$ be an array of size $|N| \times |P|$ are the latent annotations and $Z \equiv \{z_i \in \{0,1,9\}: i\in N\}$ is the experimental data (some missings, 9), we measure the quality of the imputation as

$$
\left\| A_m - \hat A_m \right\|^\mathbf{t} \mathbf{W}^{-1}_m\left\| A_m - \hat A_m \right\|
$$

where $A_m \equiv\{a_i \in A: z_i = 9\}$, the real annotations of the imputed genes, $\tilde A_m \equiv \{\hat a_i: z_i = 9\}$ the predicted annotations of the imputed genes, and $\mathbf{W}$ is a weighting matrix of size $|A_m|^2$, in particular, the shortest path length between all nodes with $z_i = 9$.

It can be shown that the previous expression can be written as

$$
\delta = \sum_{i,j}\left[\sum_{p,r} (a_{ip} - \hat a_{ir})^2(a_{jr} - \hat a_{jr})^2\right]^{1/2}w_{ij}^{-1}
$$

So, $\mbox{E}\left(\delta\right)$ reduces to computing the following

$$
\sum_{i,j} w_{ij}^{-1}\mbox{E}\left[\sum_{p,r} (a_{ip} - \hat a_{ir})^2(a_{jr} - \hat a_{jr})^2\right]^{1/2}
$$