FROM rocker/r-devel-ubsan-clang

RUN apt update && apt install --no-install-suggests -y libssl-dev

RUN \
	RDscript -e 'utils::install.packages(c("fmcmc", "MASS", "ape", "coda", "tinytest", "xml2"))'

RUN RDscript -e 'utils::install.packages("lattice")'

RUN RDscript -e 'utils::install.packages(c("knitr", "rmarkdown"))'

RUN RDscript -e 'utils::install.packages("AUC")'


CMD ["bash"]



