# Thanks to https://github.com/Enchufa2/r-flexiblas
FROM fedora:rawhide

RUN dnf install R flexiblas-* -y

# Clonning tag v3.3.1 from the repo flexiblas
RUN dnf install R-flexiblas -y

RUN echo 'options(repos=c(CRAN="https://cloud.r-project.org"))' >> ~/.Rprofile

RUN \
	Rscript -e 'utils::install.packages(c("fmcmc", "MASS", "ape", "coda", "tinytest", "xml2"))'

RUN Rscript -e 'utils::install.packages("lattice")'

RUN Rscript -e 'utils::install.packages(c("knitr", "rmarkdown"))'

RUN Rscript -e 'utils::install.packages("AUC")'

CMD ["bash"]