FROM rocker/tidyverse:4.5.1

# RUN \
#   echo 'options(repos=c(CRAN="https://packagemanager.posit.co/cran/__linux__/bookworm/latest"))' >> ~/.Rprofile && \
#   Rscript --vanilla -e 'getOption("repos")'

# Adding R packages
RUN install2.r --error roxygen2 tinytest covr knitr \
  devtools

RUN install2.r --error languageserver && \
  installGithub.r nx10/httpgd

RUN apt-get update && apt-get install --no-install-recommends -y valgrind gdb \
  libglpk-dev

# Installing additional package dependencies
RUN install2.r --error Rcpp coda fmcmc rmarkdown AUC ape

CMD ["bash"]
