// [[Rcpp::depends(RcppArmadillo)]]
#include <RcppArmadillo.h>
using namespace Rcpp;

//' Matrix of states
//' 
//' @param P Integer scalar. Number of functions.
//' @return A matrix of size 2^P by P with all the possible
//' (0,1) combinations of functions.
//' @examples
//' states(3)
//' @export
// [[Rcpp::export]]
arma::imat states(
    int P
  ) {
  
  // Creating output matrix
  int nstates = pow(2, P);
  arma::imat ans(nstates, P);
  
  // Go through states
  for (int i=0; i<nstates; i++) {
    int x=i;
    
    // Go through functions
    for (int p=0; p<P; p++) {
      ans.at(i, p) = x%2;
      x /= 2;
    }
  }
  
  return ans;
}

//' Leaf probabilities
//' 
//' @param Z A matrix of size \eqn{N\times P}{N*P} with values \code{(0,1,9)}.
//' @param S A matrix of size \eqn{2^P*P} as returned by \code{\link{states}}.
//' @param psi A numeric vector of length 2.
//' @param noffspring A numeric vector of length \eqn{N}. Number of offspring
//' per node.
//' 
//' @export
// [[Rcpp::export]]
arma::mat leaf_prob(
    const arma::imat & Z,
    const arma::imat & S,
    const arma::vec  & psi,
    const arma::ivec & noffspring
  ) {
  
  // Obtaining relevant constants
  int P       = S.n_cols;
  int N       = Z.n_rows;
  int nstates = S.n_rows;
  
  // Checking dimmensions
  if (P != (int) Z.n_cols)
    stop("Z must have the same number of columns than S.");
  
  if (2u != psi.n_elem)
    stop("psi must be of length 2.");
  
  // Creating the output matrix (probabilities)
  arma::mat ans(N,nstates);
  ans.ones();

  for (int i=0; i<N; i++)
    // Only compute for offspring (and nodes with no NA)
    if (!noffspring.at(i)) 
      for (int s=0; s<nstates; s++)
        for (int p=0; p<P; p++) {
          
          // If missing (no experimental data)
          if (Z.at(i,p) == 9)
            continue;
          
          ans.at(i, s) *=
            (Z.at(i, p) == S.at(s, p))? // Are these equal?
            (1 - psi.at(S.at(s, p))):   // TRUE
            psi.at(S.at(s, p));         // FALSE (misclasified)
          
        }
      
  return ans;
}

//' Gain/Loss probabilities
//' 
//' Generates a 2x2 matrix with gain loss probabilities, with rows and columns
//' corresponding to states (0,1) of parent and offspring respectively.
//' 
//' @param mu A numeric vector of length 2. Gain and Loss probailities.
//' 
//' @return a 2x2 matrix with gain loss probabilities, with rows and columns
//' corresponding to states (0,1) of parent and offspring respectively.
//' @export
// [[Rcpp::export]]
arma::mat gain_loss_prob(
    const arma::vec & mu
  ) {
  arma::mat ans(2,2);
  
  for (int i=0; i<2; i++)
    for (int j=0; j<2; j++) 
      ans.at(i,j) = !i ? ( j? mu.at(0) : (1-mu.at(0)) ) :
      ( !j? mu.at(1) : (1-mu.at(1)) );
    
  return ans;
}

//' Root node probabilities
//' 
//' @param pi A numeric vector of length 2 with root node probabilities.
//' @param S A numeric matrix of size 2^PxP with all possible states as
//' generated by \code{\link{states}}
//' 
//' Generates a vector of length 2^P with the root node probabilities
//' per state
//' @export
// [[Rcpp::export]]
arma::vec root_node_prob(
    const arma::vec  & pi,
    const arma::imat & S
) {
  // Obtaining relevant constants
  int P       = S.n_cols;
  int nstates = S.n_rows;
  
  arma::vec ans(nstates);
  ans.ones();
  
  for (int s=0; s<nstates; s++)
    for (int p=0; p<P; p++)
      ans.at(s) *= pi.at(S.at(s,p));
  
  return ans;
}

//' Internal node probabilities
//' 
//' @param Pr Probabilities (already with leaf probs).
//' @param M Gain/Loss probabilities (see equation 4 of math.pdf)
//' @param S States
//' @param noffspring Number of offspring
//' @param offspring List of offspring
//' @export
// [[Rcpp::export]]
arma::mat internal_prob(
  arma::mat          Pr,
  const arma::mat  & M,
  const arma::imat & S,
  const arma::ivec & noffspring,
  const List       & offspring
) {
  
  // Obtaining relevant constants
  int P       = S.n_cols;
  int N       = Pr.n_rows;
  int nstates = S.n_rows;
  
  for (int n=(N-1); n>=0; n--) {
    
    // Only for internal nodes
    if (!noffspring.at(n))
      continue;
    
    // Parent node states integration
    for (int s=0; s<nstates; s++) {
    
      // Obtaining list of offspring
      IntegerVector O(offspring.at(n));
      
      // Loop through offspring
      double offspring_joint_likelihood = 1.0;
      for (int o_n=0; o_n<noffspring.at(n) ; o_n++) {

        // Offspring states integration
        double offspring_likelihood = 0.0;
        for (int s_n=0; s_n<nstates; s_n++) {
          double s_n_sum = 1.0;
          
          // Loop through functions
          for (int p=0; p<P; p++) 
            s_n_sum *= M.at(S.at(s,p), S.at(s_n,p));
          
          // Multiplying by prob of offspring
          offspring_likelihood += ( s_n_sum * Pr.at(O.at(o_n), s_n) );
          
        }
        
        // Multiplying with other offspring
        offspring_joint_likelihood *= offspring_likelihood;
        
      }
      
      // Adding state probability
      Pr.at(n, s) = offspring_joint_likelihood;
      
    }
  }
  
  return Pr;
}

//' Computes Log-likelihood
//' 
//' This function computes the log-likelihood of the chosen parameters given
//' a particular dataset. The arguments \code{Z}, \code{offspring}, and
//' \code{noffspring} should be as those returned by \code{\link{get_offspring}}.
//' For complete Maximum Likelihood Estimation see \code{\link{mle}}.
//' 
//' @param Z A numeric matrix of size \eqn{N\times P}{N*P} with the function
//' states of each leaf (experimental data).
//' @param offspring A List of length \eqn{N} with the set of offspring of
//' each node.
//' @param noffspring An integer vector of length \eqn{N} with the number of
//' offspring per node.
//' @param psi A numeric vector of length 2 (see details).
//' @param mu A numeric vector of length 2 (see details).
//' @param Pi A numeric vector of length 2 (see details).
//' 
//' @details
//' The parameters to estimate are described as follows:
//' \enumerate{
//' \item{\code{psi}: A vector of length 2 with \eqn{\psi_0}{psi[0]} and
//' \eqn{\psi_1}{psi[1]}, which are the misclassification probabilities fo
//' \eqn{s_p=0}{s[p]=0} and \eqn{s_p=1}{s[p]=1}
//' respectively.}
//' \item{\code{mu}: A vector of length 2 with \eqn{\mu_0}{mu[0]} and
//' \eqn{\mu_1}{mu[1]} which are the gain and loss probabilities respectively.}
//' \item{\code{Pi}: A vector of length 2 with \eqn{\pi_0}{pi[0]}} and
//' \eqn{\pi_1}{pi[1]}, which for now is specified as \eqn{(1 - \pi_1)}{(1 - pi[0]),
//' which holds the root node probabilities.}
//' }
//' @return A list of class \code{phylo_LogLik} with the following elements:
//' \item{S}{An integer matrix of size \eqn{2^p\times p}{2^p * p} as returned
//' by \code{\link{states}}.}
//' \item{PI}{A numeric vector of size \eqn{2^p} with each given state's root
//' node probabilities.}
//' \item{PSI}{A numeric matrix of size \eqn{G\times 2^p}{G * 2^p} with node/state
//' probabilities only including leaf node probabilities (this is for debugging).}
//' \item{Pr}{A numeric matrix of size \eqn{G\times 2^p}{G * 2^p} with node/state
//' probabilities.}
//' \item{ll}{A numeric scalar with the log-likelihood value given the chosen
//' parameters.}
//' @export
// [[Rcpp::export]]
List LogLike(
    const arma::imat & Z,
    const List       & offspring,
    const arma::ivec & noffspring,
    const arma::vec  & psi,
    const arma::vec  & mu,
    const arma::vec  & Pi
) {

  // Obtaining States, PSI, Gain/Loss probs, and root node probs
  arma::imat S  = states(Z.n_cols);
  int nstates   = (int) S.n_rows;
  arma::mat PSI = leaf_prob(Z, S, psi, noffspring);
  arma::mat M   = gain_loss_prob(mu);
  arma::vec PiP = root_node_prob(Pi, S);
  
  // Computing likelihood
  arma::mat Pr  = internal_prob(PSI, M, S, noffspring, offspring);
  
  // We only use the root node
  double ll = 0.0;
  
  for (int s = 0; s<nstates; s++)
    ll += log(PiP.at(s)*Pr.at(0, s));
  
  // return ll;
  List ans = List::create(
    _["S"]   = S,
    _["PI"]  = PiP,
    _["PSI"] = PSI,
    _["Pr"]   = Pr,
    _["ll"]  = ll
  );
  
  ans.attr("class") = "phylo_LogLik";
  
  return(ans);
  
}

