# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix of states
#' 
#' @param P Integer scalar. Number of functions.
#' @return A matrix of size 2^P by P with all the possible
#' (0,1) combinations of functions.
#' @examples
#' states(3)
#' @export
states <- function(P) {
    .Call('phylogenetic_states', PACKAGE = 'phylogenetic', P)
}

#' Leaf probabilities
#' 
#' @param Z A matrix of size \eqn{N\times P}{N*P} with values \code{(0,1,9)}.
#' @param S A matrix of size \eqn{2^P*P} as returned by \code{\link{states}}.
#' @param psi A numeric vector of length 2.
#' @param noffsprings A numeric vector of length \eqn{N}. Number of offsprings
#' per node.
#' 
#' @export
leaf_prob <- function(Z, S, psi, noffsprings) {
    .Call('phylogenetic_leaf_prob', PACKAGE = 'phylogenetic', Z, S, psi, noffsprings)
}

#' Gain/Loss probabilities
#' 
#' Generates a 2x2 matrix with gain loss probabilities, with rows and columns
#' corresponding to states (0,1) of parent and offspring respectively.
#' 
#' @param mu A numeric vector of length 2. Gain and Loss probailities.
#' 
#' @return a 2x2 matrix with gain loss probabilities, with rows and columns
#' corresponding to states (0,1) of parent and offspring respectively.
#' @export
gain_loss_prob <- function(mu) {
    .Call('phylogenetic_gain_loss_prob', PACKAGE = 'phylogenetic', mu)
}

#' Root node probabilities
#' 
#' @param pi A numeric vector of length P with root node probabilities.
#' @param S A numeric matrix of size 2^PxP with all possible states as
#' generated by \code{\link{states}}
#' 
#' Generates a vector of length 2^P with the root node probabilities
#' per state
#' @export
root_node_prob <- function(pi, S) {
    .Call('phylogenetic_root_node_prob', PACKAGE = 'phylogenetic', pi, S)
}

#' Internal node probabilities
#' 
#' @param Pr Probabilities (already with leaf probs).
#' @param M Gain/Loss probabilities (see equation 4 of math.pdf)
#' @param S States
#' @param noffsprings Number of offsprings
#' @param offsprings List of offsprings
#' @export
internal_prob <- function(Pr, M, S, noffsprings, offsprings) {
    .Call('phylogenetic_internal_prob', PACKAGE = 'phylogenetic', Pr, M, S, noffsprings, offsprings)
}

#' Computes Log-likelihood
#' 
#' @param Z A numeric matrix of size \eqn{N\times P}{N*P} with the function
#' states of each leaf.
#' @param offsprings A List of length \eqn{N} with the set of offsprings of
#' each node.
#' @param noffsprings An integer vector of length \eqn{N} with the number of
#' offsprings per node.
#' @param psi A numeric vector of length 2.
#' @param mu A numeric vector of length 2.
#' @param Pi A numeric vector of length 2.
#' 
#' @export
LogLike <- function(Z, offsprings, noffsprings, psi, mu, Pi) {
    .Call('phylogenetic_LogLike', PACKAGE = 'phylogenetic', Z, offsprings, noffsprings, psi, mu, Pi)
}

