# Builds the tar.gz file to be uploaded to CRAN
# Using the latest version of R.
name: Build and upload

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: devtools

      - name: Build package
        run: |
          R CMD build .

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: R-package
          path: "*.tar.gz"